### ISSUE TITLE
Problem logging in

### ISSUE THREAD

**Issue by swent** [inwx/nodejs-client#14]
Hello,

I have been using this client for a while but in recent month I started failing the log in:
`
Request (account.login): {"method":"account.login","params":{"user":"???","pass":"???"}}
Response (account.login): {"code":2200,"msg":"Authentication error"}
`

This is the test code I am using:
```
const { ApiClient, Language } = require('domrobot-client');

const loginUsername = '???';
const loginPassword = '???';
const apiClient = new ApiClient(ApiClient.API_URL_OTE, Language.EN, true);

async function test() {
    const loginResponse = await apiClient.login(loginUsername, loginPassword);
    if (loginResponse.code !== 1000) {
        console.error('Api error: ' + loginResponse.code + ' message: ' + loginResponse.msg);
    } else {
        console.log('Successfully logged in !');
    }
}

test();
```

**Versions:**
Package: 3.0.2
OS: windows 10
Node: 14.18.0

I double checked that the same credentials can be used to log into the web-site.
Help would be appreciated.

Best regards,
Lutz

**Comment by NickUfer** [comment]
Hi, you are using our OTE/testing API.

```
... new ApiClient(ApiClient.API_URL_OTE, ...
```

The production (inwx.com) and OTE (ote.inwx.com) environments don't share any data or user accounts. I assume you've got an account in the production environment and you try to log in in the testing environment. Using `ApiClient.API_URL_LIVE` instead of `ApiClient.API_URL_OTE` should do the trick.
